### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by qumuq-til** [theojulienne/covid-19-graphics#7]
One thing that bugs me personally is the choice of icons for deaths and recovered. The sad-sad-tear-tear icon kinda subverts the notion of death by replacing it with an instagram-era virtual something that is not real. More appropriate choice would be a skull, it's a familiar icon that's been historically used extensively in various places, to denote danger to life.

Similarly, recovered icon is a happy face but it's been reported that not all recoveries are complete and without issues and there's also a chance of being re-infected again. Don't know what would be more appropriate in this case. Thumbs up is a bit overoptimistic as well but could work.

Confirmed cases could use a classical red cross symbol outline.

**Comment by theojulienne** [comment]
I agree this is difficult. What do you think of removing the icons altogether?

The aim of the site was/is to provide visual indicators of the available data without adding anything subjective. I don't think the icons really add anything to that aim, they only exist because the template had a place for them, so I'd be happy to remove them.

**Comment by qumuq-til** [comment]
Actually that might be a very good idea. This is not entertainment after all, so just leaving plain old text would make the information look more serious and professional.

**Comment by theojulienne** [comment]
:+1: I'm removing them in https://github.com/theojulienne/covid-19-graphics/pull/8
